version: '3.9'
services:
  postgres:
    image: postgis/postgis
    container_name: nestjs-postgres
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: artem
      POSTGRES_DB: to-do api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: